# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spectate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spectate.proto',
  package='spectate',
  syntax='proto3',
  serialized_pb=_b('\n\x0espectate.proto\x12\x08spectate\"=\n\x0bSPECjbbPair\x12\x11\n\tprop_name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\"\x93\x01\n\x10RunConfiguration\x12\x0c\n\x04java\x18\x01 \x01(\t\x12\x0b\n\x03jar\x18\x02 \x01(\t\x12\x14\n\x0cjava_options\x18\x03 \x03(\t\x12\x14\n\x0cspec_options\x18\x04 \x03(\t\x12\x12\n\nprops_file\x18\x05 \x01(\t\x12$\n\x05props\x18\x06 \x03(\x0b\x32\x15.spectate.SPECjbbPair\"(\n\x10\x42\x65nchmarkResults\x12\x14\n\x0cresults_path\x18\x01 \x01(\t2g\n\x19SPECtateDistributedRunner\x12J\n\x0e\x44oBenchmarkRun\x12\x1a.spectate.RunConfiguration\x1a\x1a.spectate.BenchmarkResults\"\x00\x62\x06proto3')
)




_SPECJBBPAIR = _descriptor.Descriptor(
  name='SPECjbbPair',
  full_name='spectate.SPECjbbPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prop_name', full_name='spectate.SPECjbbPair.prop_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='spectate.SPECjbbPair.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='spectate.SPECjbbPair.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=89,
)


_RUNCONFIGURATION = _descriptor.Descriptor(
  name='RunConfiguration',
  full_name='spectate.RunConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='java', full_name='spectate.RunConfiguration.java', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='jar', full_name='spectate.RunConfiguration.jar', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='java_options', full_name='spectate.RunConfiguration.java_options', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spec_options', full_name='spectate.RunConfiguration.spec_options', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='props_file', full_name='spectate.RunConfiguration.props_file', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='props', full_name='spectate.RunConfiguration.props', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=239,
)


_BENCHMARKRESULTS = _descriptor.Descriptor(
  name='BenchmarkResults',
  full_name='spectate.BenchmarkResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results_path', full_name='spectate.BenchmarkResults.results_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=281,
)

_RUNCONFIGURATION.fields_by_name['props'].message_type = _SPECJBBPAIR
DESCRIPTOR.message_types_by_name['SPECjbbPair'] = _SPECJBBPAIR
DESCRIPTOR.message_types_by_name['RunConfiguration'] = _RUNCONFIGURATION
DESCRIPTOR.message_types_by_name['BenchmarkResults'] = _BENCHMARKRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SPECjbbPair = _reflection.GeneratedProtocolMessageType('SPECjbbPair', (_message.Message,), dict(
  DESCRIPTOR = _SPECJBBPAIR,
  __module__ = 'spectate_pb2'
  # @@protoc_insertion_point(class_scope:spectate.SPECjbbPair)
  ))
_sym_db.RegisterMessage(SPECjbbPair)

RunConfiguration = _reflection.GeneratedProtocolMessageType('RunConfiguration', (_message.Message,), dict(
  DESCRIPTOR = _RUNCONFIGURATION,
  __module__ = 'spectate_pb2'
  # @@protoc_insertion_point(class_scope:spectate.RunConfiguration)
  ))
_sym_db.RegisterMessage(RunConfiguration)

BenchmarkResults = _reflection.GeneratedProtocolMessageType('BenchmarkResults', (_message.Message,), dict(
  DESCRIPTOR = _BENCHMARKRESULTS,
  __module__ = 'spectate_pb2'
  # @@protoc_insertion_point(class_scope:spectate.BenchmarkResults)
  ))
_sym_db.RegisterMessage(BenchmarkResults)



_SPECTATEDISTRIBUTEDRUNNER = _descriptor.ServiceDescriptor(
  name='SPECtateDistributedRunner',
  full_name='spectate.SPECtateDistributedRunner',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=283,
  serialized_end=386,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoBenchmarkRun',
    full_name='spectate.SPECtateDistributedRunner.DoBenchmarkRun',
    index=0,
    containing_service=None,
    input_type=_RUNCONFIGURATION,
    output_type=_BENCHMARKRESULTS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPECTATEDISTRIBUTEDRUNNER)

DESCRIPTOR.services_by_name['SPECtateDistributedRunner'] = _SPECTATEDISTRIBUTEDRUNNER

# @@protoc_insertion_point(module_scope)
